/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cache Stats
         * @description Diagnostic — requires auth in production.
         */
        get: operations["cache_stats_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rag Stats
         * @description Diagnostic — requires auth in production.
         */
        get: operations["rag_stats_rag_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rag Preview
         * @description Diagnostic: see what chunks RAG retrieves for a query. Requires auth.
         */
        get: operations["rag_preview_rag_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze-vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Analyze Vitals */
        post: operations["post_analyze_vitals_analyze_vitals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat */
        post: operations["post_chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Chat Stream
         * @description Server-Sent Events stream of the LLM response.
         *
         *     Protocol:
         *       event: start       -> (open the stream)
         *       event: chunk       -> data: {"text": "partial"}
         *       event: final       -> data: {"full_answer", "emergency", "severity", ...}
         *
         *     Mobile app consumes this via EventSource or a polyfill.
         */
        post: operations["post_chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeVitalsResponse */
        AnalyzeVitalsResponse: {
            /** Severity */
            severity: string;
            /** Summary */
            summary: string | null;
            /** Alerts */
            alerts: {
                [key: string]: unknown;
            }[];
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Chat History */
            chat_history?: components["schemas"]["ChatMessage"][] | null;
            vitals?: components["schemas"]["Vitals"] | null;
            patient?: components["schemas"]["Patient"] | null;
            /** Activity */
            activity?: ("sitting" | "walking" | "running" | "climbing_stairs" | "going_downstairs" | "sleeping" | "standing" | "lying") | null;
            /** Recent Events */
            recent_events?: components["schemas"]["HealthEvent"][] | null;
            /** User Role */
            user_role?: ("wearer" | "caregiver") | null;
            /**
             * Vitals Trend
             * @description Optional short trend summary, e.g. 'HR rose 70->95 over 2h'
             */
            vitals_trend?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Refused */
            refused: boolean;
            /** Model */
            model: string;
            /** Severity */
            severity?: string | null;
            /** Vitals Summary */
            vitals_summary?: string | null;
            /**
             * Emergency
             * @default false
             */
            emergency: boolean;
            /** Emergency Reason */
            emergency_reason?: string | null;
            /**
             * Recommended Action
             * @default none
             * @enum {string}
             */
            recommended_action: "call_911" | "contact_caregiver" | "monitor" | "none";
            /**
             * Red Flags
             * @default []
             */
            red_flags: components["schemas"]["RedFlagOut"][];
            /**
             * Drug Warnings
             * @default []
             */
            drug_warnings: components["schemas"]["DrugWarningOut"][];
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourceOut"][];
            /**
             * Follow Ups
             * @default []
             */
            follow_ups: string[];
            /**
             * @default {
             *       "key_points": [],
             *       "recommendations": []
             *     }
             */
            structured: components["schemas"]["StructuredOut"];
            /** @default {} */
            usage: components["schemas"]["UsageOut"];
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** DrugWarningOut */
        DrugWarningOut: {
            /** Level */
            level: string;
            /** Category */
            category: string;
            /** Drugs */
            drugs: string[];
            /** Message */
            message: string;
            /** Citation */
            citation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthEvent */
        HealthEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "fall" | "tachycardia" | "hypoxia" | "geofence_exit" | "sos" | "other";
            /**
             * When
             * @description Human-readable time, e.g. '3 min ago' or ISO timestamp
             */
            when: string;
            /** Detail */
            detail?: string | null;
        };
        /** Patient */
        Patient: {
            /** Age */
            age?: number | null;
            /** Sex */
            sex?: ("M" | "F") | null;
            /** Conditions */
            conditions?: string[] | null;
            /** Medications */
            medications?: string[] | null;
        };
        /** RedFlagOut */
        RedFlagOut: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Severity */
            severity: string;
            /** Matched Text */
            matched_text: string;
        };
        /**
         * SourceOut
         * @description One retrieved corpus chunk supporting the answer.
         */
        SourceOut: {
            /** Source */
            source: string;
            /** Chunk */
            chunk: number;
            /** Snippet */
            snippet: string;
        };
        /**
         * StructuredOut
         * @description Optional parsed sections of the answer for structured rendering.
         *     Empty if the LLM didn't produce recognizable headings.
         */
        StructuredOut: {
            /** Overview */
            overview?: string | null;
            /**
             * Key Points
             * @default []
             */
            key_points: string[];
            /**
             * Recommendations
             * @default []
             */
            recommendations: string[];
            /** Emergency */
            emergency?: string | null;
        };
        /** UsageOut */
        UsageOut: {
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vitals */
        Vitals: {
            /**
             * Hr
             * @description Heart rate, bpm
             */
            hr?: number | null;
            /**
             * Spo2
             * @description Blood oxygen saturation, %
             */
            spo2?: number | null;
            /**
             * Rr
             * @description Respiratory rate, br/min (optional)
             */
            rr?: number | null;
            /**
             * Temp
             * @description Temperature, °C
             */
            temp?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cache_stats_cache_stats_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rag_stats_rag_stats_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rag_preview_rag_preview_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
            };
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_analyze_vitals_analyze_vitals_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vitals"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeVitalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
